#[soroban_sdk::contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum Error {
    AlreadyInitialized = 1,
    NotAdmin = 2,
    EscrowNotFound = 3,
    InvalidState = 4,
    NotDepositor = 5,
    NotRecipient = 6,
    NotArbiter = 7,
    NotParty = 8,
    AlreadyReleased = 9,
    AlreadyRefunded = 10,
    AlreadyDisputed = 11,
    AlreadyResolved = 12,
    NotYetDue = 13,
    Expired = 14,
    TransferFailed = 15,
    InsufficientBalance = 16,
    InvalidCondition = 17,
    QuorumNotReached = 18,
    AlreadyApproved = 19,
    NotApprover = 20,
    TooManyParties = 21,
    InvalidAmount = 22,
    Overflow = 23,
    EscrowNotActive = 24,
    EscrowNotFunded = 25,
    DuplicateParty = 26,
    InvalidTimestamp = 27,
    ConditionNotMet = 28,
    NoArbiterSet = 29,
}
